package com.uady.awsfundations.app.model;

import java.time.LocalDateTime;
import java.time.ZoneOffset;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.uady.awsfundations.app.utils.SessionStringGenerator;

import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "sesiones-alumnos")
public class Session {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "fecha")
    private Long fecha = LocalDateTime.now().toEpochSecond(ZoneOffset.UTC);

    @DynamoDBAttribute(attributeName = "alumnoId")
    private Integer alumnoId;

    @DynamoDBAttribute(attributeName = "active")
    private Boolean active = true;

    @DynamoDBAttribute(attributeName = "sessionString")
    private String sessionString = SessionStringGenerator.generateSessionString();

}
